tap "homebrew/cask"

cask_args appdir: "/Applications"

brew "fzf"
brew "git"
brew "tmux"
brew "vim"
brew "imagemagick"
brew "ffmpeg"
brew "asciinema"
brew "jq"
brew "postgresql"
brew "mysql"
brew "openssl"
brew "ansible"
brew "anyenv"
brew "mas"
brew "awscli"
brew "bat"
brew "ripgrep"
brew "exa"
brew "hexyl"
brew "fd"
brew "procs"
brew "terminal-notifier"
brew "zplug"
brew "tree"
brew "zsh"
brew "zsh-completions"
brew "yarn"
brew "gcc"
brew "cocoapods"
brew "watchman"
brew "redis"

cask "docker"
cask "virtualbox"
cask "firefox"
cask "google-chrome"
cask "google-japanese-ime"
cask "google-backup-and-sync"
cask "iterm2"
cask "karabiner-elements"
cask "visual-studio-code"
cask "arduino"
cask "discord"
cask "slack"
cask "dropbox"
cask "inkscape"
cask "kicad"
cask "skype"
cask "vlc"
cask "appcleaner"
cask "alfred"
cask "imageoptim"
cask "shiftit"
cask "aws-vault"
cask "java"
cask "adoptopenjdk"
cask "android-studio"
cask "genymotion"
cask "google-cloud-sdk"
cask "flipper"

mas "Xcode", id:497799835

