# -*- coding: utf-8-unix -*-

unbind C-b             # デフォルトのプレフィックスを解除
set -g prefix C-g      # プレフィックスの設定
set -sg escape-time 1  # キーストロークのディレイを減らす

# set -g base-index 1
# setw -g pane-base-index 1

bind r   source-file ~/.tmux.conf \; display "Relocaded!"
bind C-g send-prefix
bind c   new-window      -c '#{pane_current_path}'
bind |   split-window -h -c '#{pane_current_path}'
bind -   split-window -v -c '#{pane_current_path}'

bind-key -r Tab select-pane -t :.+

bind h  select-pane -L
bind j  select-pane -D
bind k  select-pane -U
bind l  select-pane -R
# bind -r C-h select-window -t :-
# bind -r C-l select-window -t :+

bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

set-option -g mouse off
bind-key m \
  if-shell "tmux show-options -g mouse | grep off" "set-option -g mouse on" "set-option -g mouse off" \; display-message "Toggled mouse on/off."
bind-key C-m \
  if-shell "tmux show-options -g mouse | grep off" "set-option -g mouse on" "set-option -g mouse off" \; display-message "Toggled mouse on/off."

bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

set -g default-terminal "screen-256color"

setw -g window-status-current-fg white
setw -g window-status-current-bg red
setw -g window-status-current-attr bright

set -g pane-border-fg green
set -g pane-border-bg black

set -g pane-active-border-fg white
set -g pane-active-border-bg yellow

# copy mode
set-window-option -g mode-keys vi
#set-window-option -g mode-keys emacs

# need xsel
bind-key > save-buffer ~/.tmux-buffer \; run-shell 'xsel -b -i < ~/.tmux-buffer' \; display-message "Copied to clipboard."
bind-key < if-shell 'xsel -b -o > ~/.tmux-buffer' 'load-buffer ~/.tmux-buffer ; paste-buffer'

