source $HOME/.dotfiles/vim/basic.vim
source $HOME/.dotfiles/vim/plug.vim

source $HOME/.dotfiles/vim/molokai.vim
source $HOME/.dotfiles/vim/nerdtree.vim
source $HOME/.dotfiles/vim/indent-guides.vim
source $HOME/.dotfiles/vim/quickhl.vim

